name: Build King Tap APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Change Icon Automatically
        run: |
          # هذا الأمر يجد صورتك مهما كان اسمها ويضعها كأيقونة
          YOUR_IMAGE=$(find . -maxdepth 1 -name "*.png" -not -name "ic_launcher.png" | head -1)
          find app/src/main/res -name "ic_launcher.png" -exec cp $YOUR_IMAGE {} \;
      - name: Build APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug
      - name: Upload Final APK
        uses: actions/upload-artifact@v2
        with:
          name: KingTap-With-Icon
          path: app/build/outputs/apk/debug/app-debug.apk
