herename: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create Project
        run: |
          cordova create build_dir com.king.clicker KingTap
          cd build_dir
          cordova platform add android
          # نسخ ملفك الأساسي للمجلد الصحيح
          cp ../index.html www/index.html

      - name: Build Android
        run: |
          cd build_dir
          cordova build android --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: King-Tap-Game
          path: build_dir/platforms/android/app/build/outputs/apk/debug/app-debug.apk
